# Generated by Django 2.2.2 on 2019-07-04 17:12

from django.db import migrations, models
import java_wallet.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeerMonitor',
            fields=[
                ('address', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('announced_address', models.CharField(blank=True, max_length=259)),
                ('platform', models.CharField(blank=True, max_length=255)),
                ('application', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(blank=True, max_length=255)),
                ('last_block', models.CharField(blank=True, max_length=20)),
                ('number_blocks', models.PositiveIntegerField(blank=True, default=0)),
                ('last_blockchain_feeder', models.GenericIPAddressField(blank=True, null=True)),
                ('last_blockchain_feeder_height', models.PositiveIntegerField(blank=True, default=0)),
                ('proofs_online', models.PositiveIntegerField(blank=True, default=0)),
                ('downtime', models.PositiveIntegerField(blank=True, default=0)),
                ('lifetime', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultiOut',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('height', models.IntegerField()),
                ('tx_id', java_wallet.fields.PositiveBigIntegerField()),
                ('sender_id', java_wallet.fields.PositiveBigIntegerField(db_index=True)),
                ('recipient_id', java_wallet.fields.PositiveBigIntegerField(db_index=True)),
                ('amount', java_wallet.fields.PositiveBigIntegerField()),
                ('tx_subtype', models.PositiveSmallIntegerField(choices=[(1, 'MultiOut Payment'), (2, 'MultiOutSame Payment')])),
                ('tx_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('tx_id', 'recipient_id')},
                'index_together': {('height', 'tx_timestamp')},
            },
        ),
    ]
