# Generated by Django 2.2.1 on 2019-05-30 23:34

from django.db import migrations, models
import java_wallet.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiOut',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tx_id', java_wallet.fields.PositiveBigIntegerField(db_index=True)),
                ('height', models.IntegerField(db_index=True)),
                ('sender_id', java_wallet.fields.PositiveBigIntegerField(db_index=True)),
                ('recipient_id', java_wallet.fields.PositiveBigIntegerField(db_index=True)),
                ('amount', java_wallet.fields.PositiveBigIntegerField()),
                ('tx_type', models.PositiveSmallIntegerField()),
                ('tx_timestamp', models.DateTimeField()),
            ],
        ),
    ]
